# Generated by Django 5.0.6 on 2024-06-03 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('-id',), 'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
    ]
